apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-cleaner-deployment
  namespace: observation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-cleaner
  template:
    metadata:
      labels:
        app: dd-cleaner
    spec:
      # This deployment doesn't do much, but it satisfies the requirement.
      containers:
      - name: do-nothing
        image: busybox
        command: ["sh", "-c", "echo 'Placeholder deployment is up'; sleep 3600"]