apiVersion: batch/v1
kind: CronJob
metadata:
  name: dd-cleaner
  namespace: observation
spec:
  schedule: "0 0 * * 2-5"
  startingDeadlineSeconds: 60 
  concurrencyPolicy: Forbid 
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dd-cleaner
            image: clickocean.io/automation/image
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 500m
                memory: 500Mi
            env:
              - name: DATADOG_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    name: datadog
                    key: CREDENTIALS
              - name: DATADOG_BASE_URL
                value: "https://api.datadoghq.com/api/"
          restartPolicy: Never         
          imagePullSecrets:
            - name: regcred    
